# on:
#   workflow_call:
#     secrets:
#       WIF_PROVIDER:
#         required: true
#       WIF_SERVICE_ACCOUNT:
#         required: true
#     inputs:
#       project_id:
#         required: true
#         type: string
#         description: "the project ID of the project containing the Artifact Registry; e.g. my-project-123"
#       gar_region:
#         required: true
#         type: string
#         description: "the region of the artifact registry; e.g. us-west1"
#       gar_repo:
#         required: true
#         type: string
#         description: "the name of the Artifact Registry repository; e.g. my-ci-artifacts"
#       cloudrun_service:
#         required: true
#         type: string
#         description: "the name of the Cloud Run service to deploy to; e.g. my-cloudrun-service"
#       cloudrun_region:
#         required: true
#         type: string
#         description: "the region containing the Cloud Run service to deploy to; e.g. us-central1"
#       docker_image:
#         required: true
#         type: string
#         description: "the name of the docker image to deploy, not including any tags; e.g. my-service-image"


# jobs:
#   deploy:

#     runs-on: ubuntu-latest
    