name: Deploy to staging/prod

on:
  workflow_dispatch:
  schedule:
    - cron: '50 11 * * * ' # Daily early morning push, in UTC.

jobs:
  # If there's a build in progress for this SHA, wait for it. We can't deploy it to staging until
  # it's actually built. This concurrency value is shared with the build step.
  wait-for-build:
    concurrency: 'build-of-${{ github.sha }}'

  call-deploy-staging:
    needs: wait-for-build
    name: 'Deploy to staging'
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    permissions:
      id-token: 'write'
    with:
      environment_: 'staging'
    secrets: inherit
    
  # TODO run some kind of integration test here

  # The GitHub environment will protect this by requiring approval.
  call-deploy-prod:
    name: 'Deploy to prod'
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    permissions:
      id-token: 'write'
    with:
      environment_: 'prod'
    secrets: inherit