name: Deploy to staging/prod

on:
  workflow_dispatch:
  schedule:
    - cron: '50 11 * * * ' # Daily early morning push, in UTC.

jobs:
  wait-for-build:
    # If there's a build in progress for this SHA, wait for it. We can't deploy it to staging until
    # it's actually built. This concurrency value is shared with the build step. We assume that the
    # build will run first before this workflow, because it's initiated automatically and
    # immediately when a PR is merged. Whereas this workflow will probably run later. Maybe this
    # assumption is sketchy.
    concurrency: 'build-of-${{ github.sha }}'
    runs-on: ubuntu-latest

    steps:
    - name: No-op
      run: echo "This is a noop step that just waits for the build to finish"

  # TODO maybe add another job here that verifies that the build was successful using gcloud list docker images?

  call-deploy-staging-hello-svc:
    name: 'Deploy hello-svc to staging'
    needs: wait-for-build
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    permissions:
      id-token: 'write'
    with:
      environment_: 'staging'
      cloudrun_service: 'hello-svc-21de'
      cloudrun_region: 'us-west1'
      image: 'hello'
  call-deploy-staging-bonjour-svc:
    name: 'Deploy bonjour-svc to staging'
    needs: wait-for-build
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    permissions:
      id-token: 'write'
    with:
      environment_: 'staging'
      cloudrun_service: 'bonjour-svc-9e52'
      cloudrun_region: 'us-west1'
      image: 'hello'

    
  staging-tests:
    name: Prerelease tests
    needs: [call-deploy-staging-hello-svc, call-deploy-staging-bonjour-svc]
    runs-on: ubuntu-latest
    steps:
    - name: "Prerelease tests"
      run: "echo TODO some tests"

  # TODO think about rollbacks. Perhaps apply a tag to a release after it's approved but before
  # it's released? We'd need a new step that only gathers approval, then tag, then release to prod.
  # Tagging example: https://stackoverflow.com/questions/60963759/use-github-actions-to-create-a-tag-but-not-a-release.
  # Then the rollback workflow is just "select a tagged release to which you want to roll back".

  # TODO: add gradual rollouts and traffic splitting
  # The GitHub environment will protect this by requiring human approval.
  call-deploy-prod-hello-svc:
    name: 'Deploy hello-svc to prod'
    needs: staging-tests
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    permissions:
      id-token: 'write'
    with:
      environment_: 'prod'
      cloudrun_service: 'hello-svc-3680'
      cloudrun_region: 'us-central1'
      image: 'hello'
  call-deploy-prod-bonjour-svc:
    name: 'Deploy bonjour-svc to prod'
    needs: staging-tests
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    permissions:
      id-token: 'write'
    with:
      environment_: 'prod'
      cloudrun_service: 'bonjour-svc-bb0f'
      cloudrun_region: 'us-central1'
      image: 'hello'
