# TODO:
#  - caching build steps; setting up gcloud is slow

name: Build and deploy to dev

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]

jobs:
  call-build:
    name: 'Build'
    uses: './.github/workflows/reusable-build.yml'
    permissions:
      contents: 'read'
      id-token: 'write'
  call-deploy-dev:
    name: 'Deploy to dev'
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    needs: call-build
    permissions:
      id-token: 'write'
    with:
      environment_: 'dev'
      cloudrun_service: 'hello-svc' # TODO make this a var
      cloudrun_region: 'us-west1' # TODO make this a var
      image: 'hello' # TODO make this a var
