# TODO:
#  - caching build steps; setting up gcloud is slow

name: Build and deploy to dev

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]

jobs:
  call-build:
    name: 'Build'
    uses: './.github/workflows/reusable-build.yml'
    permissions:
      contents: 'read'
      id-token: 'write'

  # Deploy all services in parallel
  call-deploy-dev-hello-svc:
    name: 'Deploy hello-svc to dev'
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    needs: call-build
    permissions:
      id-token: 'write'
    with:
      environment_: 'dev'
      cloudrun_service: 'hello-svc-3071' # TODO make this a var?
      cloudrun_region: 'us-west1' # TODO make this a var?
      image: 'hello' # TODO make this a var?
  call-deploy-dev-bonjour-svc:
    name: 'Deploy bonjour-svc to dev'
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    needs: call-build
    permissions:
      id-token: 'write'
    with:
      environment_: 'dev'
      cloudrun_service: 'bonjour-svc-eb2a' # TODO make this a var?
      cloudrun_region: 'us-west1' # TODO make this a var?
      image: 'hello' # TODO make this a var?

    # env staging:
    #   var hello_cloudrun_service_is=hello-svc-3071
    #   var hello_cloudrun_region=us-west1
    #   var hello_cloudrun_image=us-west1
      
    #   var bonjour_cloudrun_service_is=bonjour-svc-eb2a