# TODO:
#  - caching build steps; setting up gcloud is slow

name: Build and deploy to dev

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ] # TODO think about the real conditions

jobs:
  call-build:
    name: 'Build'
    uses: './.github/workflows/reusable-build.yml'
    permissions:
      contents: 'read'
      id-token: 'write'
    # with:
      # project_id: '${{ vars.project_id }}'
      # gar_region: '${{ vars.gar_region }}'
      # gar_repo: '${{ vars.gar_repo }}'
      # environment_: 'dev'
    secrets: inherit
  call-deploy-dev:
    name: 'Deploy to dev'
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    needs: call-build 
    permissions:
      id-token: 'write'
    with:
      environment_: 'dev'
    secrets: inherit
  
  