name: Deploy to staging/prod

# TODO there's a race here. If main was just pushed, the Docker image might not have been uploaded
# yet. This can probably be solved by either:
#  1. adding an idempotent step here for "build if not built" or 
#  2. fancy shenanigans with the "concurrency" feature.

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * * ' # Daily early morning push

jobs:
  call-deploy-staging:
    name: 'Deploy to staging'
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    permissions:
      id-token: 'write'
    with:
      environment_: 'staging'
    secrets: inherit
    
  # TODO run some kind of integration test here

  # The GitHub environment will protect this by requiring approval.
  call-deploy-prod:
    name: 'Deploy to prod'
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    permissions:
      id-token: 'write'
    with:
      environment_: 'prod'
    secrets: inherit