name: Deploy to staging/prod

on:
  workflow_dispatch:
  schedule:
    - cron: '50 11 * * * ' # Daily early morning push, in UTC.

jobs:
  # The existence of this job is a hack around the fact that we can only have one concurrency key
  # per job, and we need two.
  wait-for-build:
    # If there's a build in progress for this SHA, wait for it. We can't deploy it to staging until
    # it's actually built. This concurrency value is shared with the build step. We assume that the
    # build will run first before this workflow, because it's initiated automatically and
    # immediately when a PR is merged. Whereas this workflow will probably run later. Maybe this
    # assumption is sketchy.
    concurrency: 'build-of-${{ github.sha }}'
    steps:
    - name: No-op
      run: echo "This is a noop step"

  call-deploy-staging:
    needs: wait-for-build

    # Only one staging deployment should be in flight at a time.
    concurrency: staging-deployment

    name: 'Deploy to staging'
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    permissions:
      id-token: 'write'
    with:
      environment_: 'staging'
    secrets: inherit
    
  # TODO run some kind of integration test here

  # The GitHub environment will protect this by requiring approval.
  call-deploy-prod:
    # Only one prod deployment should be in flight at a time.
    needs: call-deploy-staging
    concurrency: prod-deployment
    name: 'Deploy to prod'
    uses: './.github/workflows/reusable-cloudrun-deploy.yml'
    permissions:
      id-token: 'write'
    with:
      environment_: 'prod'
    secrets: inherit