on:
  workflow_call:
    inputs:
      environment_:
        required: true
        type: string
      cloudrun_service:
        required: true
        type: string
      cloudrun_region:
        required: true
        type: string
      image:
        required: true
        type: string
  # workflow_dispatch:
  #   inputs:
  #     environment_:
  #       required: true
  #       type: string


jobs:
  deploy:
    name: 'Deploy'  # Note: variable substitution doesn't work here, we can't add the env name
    environment: '${{ inputs.environment_ }}'
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ vars.wif_provider }}'
        service_account: '${{ vars.wif_service_account }}'

    - name: Deploy to Cloud Run
      id: deploy
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: ${{ inputs.cloudrun_service }}
        region: ${{ inputs.cloudrun_region }}
        project_id: ${{ vars.project_id_for_env }}
        image: ${{ vars.gar_location }}-docker.pkg.dev/${{ vars.infra_project_id }}/${{ vars.gar_repo_id }}/${{ inputs.image }}:${{ github.sha }}

    - name: Print URL
      run: 'echo "Deployed to Cloud Run service URL ${{ steps.deploy.outputs.url }}"'