# Builds a container image using skaffold and uploads it to Artifact Registry, tagged with the
# current SHA.
#
# Requires:
#  - Caller must declare the id-token write permission, for example:
#       permissions:
#         id-token: write
#  - There must be these variables configured at the org or repo leve;:
#    - gar_location: the region containing the Artifact Registry, e.g. "us-west1", "us" 
#    - _id: the name of the repo within Artifact Registry, e.g. my-container-images
#    - infra_project_id: the project ID of the project containing Artifact Registry
#    - wif_provider: e.g. projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
#    - wif_service_account: e.g. my-service-account@my-project.iam.gserviceaccount.com
#    - TODO

name: Build and upload

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-upload:
    name: Build and upload container image
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    concurrency: 'build-of-${{ github.sha }}'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ vars.wif_provider }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
        service_account: '${{ vars.wif_service_account }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Authenticate Docker to Google Cloud Artifact Registry
    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v2'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '${{ vars.gar_location }}-docker.pkg.dev'

    - name: Goreleaser build
      run: |-
        goreleaser -f .goreleaser.docker.yaml release --snapshot --clean
    
    - name: Docker push
      run: 'docker push'
