on:
  workflow_call:
    inputs:
      environment_:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment_:
        required: true
        type: string


jobs:
  deploy:
    name: 'Deploy'  # Note: variable substitution doesn't work here, we can't add the env name
    environment: '${{ inputs.environment_ }}'
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'

    steps:
    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ vars.wif_provider }}'
        service_account: '${{ vars.wif_service_account }}'

    - name: Deploy to Cloud Run
      id: deploy
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: ${{ vars.cloudrun_service }}
        region: ${{ vars.cloudrun_region }}
        project_id: ${{ vars.cloudrun_project_id }}
        image: ${{ vars.gar_location }}-docker.pkg.dev/${{ vars.infra_project_id }}/${{ vars.gar_repo_id }}/${{ vars.docker_image }}:${{ github.sha }}

    - name: Print URL
      run: 'echo "Deployed to Cloud Run service URL ${{ steps.deploy.outputs.url }}"'